[package]
name = "imu-calib"
version = "0.3.0"
edition = "2021"
authors = ["Christopher Sieh <stelzo@steado.de>"]
description = "Kalibr-compatible IMU intrinsic calibration and correction library for Rust."
repository = "https://codeberg.com/stelzo/imu-calib"
license = "MIT OR Apache-2.0"
keywords = ["ros", "imu", "calibration"]
categories = [
    "science::robotics",
]
readme = "README.md"
documentation = "https://docs.rs/imu-calib"
homepage = "https://codeberg.com/stelzo/imu-calib"
exclude = [
    "**/.github/**",
    "**/tests/**",
    "**/examples/**",
    "**/benches/**",
    "**/target/**",
    "**/build/**",
    "**/dist/**",
    "**/docs/**",
    "**/doc/**",
    "**/ensure_no_std/**",
]
rust-version = "1.89.0"

[features]
default = ["kalibr"]
kalibr = ["serde", "dep:serde_yaml"]
serde = ["dep:serde"]

[dependencies]
anyhow = "1.0"
nalgebra = "0.35"
serde = { version = "1", features = ["derive"], optional = true }
serde_yaml = { version = "0.9", optional = true }
